/**
 * prisma.ts
 *
 * This file creates and exports a single Prisma client instance
 * that the whole application can use to access the database.
 *
 * In a Next.js app, this avoids creating multiple DB connections
 * during development (because the dev server reloads modules often).
 */

// Import the generated Prisma Client (generated by `prisma generate`)
import { PrismaClient } from "@/generated/prisma/client";

// Import the SQLite adapter that lets Prisma use the better-sqlite3 driver
import { PrismaBetterSqlite3 } from "@prisma/adapter-better-sqlite3";

/**
 * Read the database connection string from environment variables.
 *
 * Example (.env):
 * DATABASE_URL="file:./dev.db"
 *
 */
const connectionString = process.env.DATABASE_URL;

if (!connectionString) {
  throw new Error("DATABASE_URL is not defined.");
}

/**
 * Create the adapter that Prisma will use to talk to SQLite.
 *
 * Normally Prisma talks directly to the database driver.
 * Here we explicitly tell it to use the `better-sqlite3` driver.
 */
const adapter = new PrismaBetterSqlite3({
  url: connectionString,
});

/**
 * Next.js development servers reload modules frequently.
 * Without protection, every reload would create a new Prisma client.
 *
 * That eventually causes errors like:
 * "Too many Prisma Clients are already running"
 *
 * So we store the Prisma instance on the global object
 * and reuse it across reloads.
 */
const globalForPrisma = globalThis as unknown as {
  prisma?: PrismaClient;
};

/**
 * If a Prisma client already exists globally, reuse it.
 * Otherwise create a new one.
 */
export const prisma =
  globalForPrisma.prisma ??
  new PrismaClient({
    adapter,
  });

/**
 * In development we save the Prisma client globally.
 * In production this step is skipped because the app
 * does not hot-reload modules.
 */
if (process.env.NODE_ENV !== "production") {
  globalForPrisma.prisma = prisma;
}
