import type { Metadata } from "next";
import "./globals.css";
import { Inter, Inika } from "next/font/google";
import { Gentium_Book_Plus } from "next/font/google";
import { QueryProvider } from "@/providers/QueryProvider";
import { ThemeProvider } from "@/providers/ThemeProvider";
import { Toaster } from "sonner";
import { Header } from "@/components/header/Header";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const inika = Inika({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-inika",
});

const gentium = Gentium_Book_Plus({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-gentium",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${inter.variable} ${inika.variable} ${gentium.variable}`}
    >
      <body>
        <ThemeProvider>
          <QueryProvider>
            <Toaster position="top-right" />
            <Header />
            {children}
          </QueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
